// Test inputs and page helpers. Audio inputs are generated on the fly (audio files are git-ignored);
// the only personal recording ever used is an optional local one from spike/recordings.
import { existsSync, mkdirSync, readdirSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import type { Browser } from "@e2e-dev/web";

/**
 * Writes a silent 8 kHz mono 8-bit PCM WAV of `seconds` length to `path` (relative to spike/) and
 * returns that path, ready for setInputFiles.
 */
export function silentWav(path: string, seconds: number): string {
  const sampleRate = 8000;
  const dataSize = sampleRate * seconds;
  const buf = Buffer.alloc(44 + dataSize, 128); // 128 is silence for unsigned 8-bit PCM
  buf.write("RIFF", 0, "ascii");
  buf.writeUInt32LE(36 + dataSize, 4);
  buf.write("WAVE", 8, "ascii");
  buf.write("fmt ", 12, "ascii");
  buf.writeUInt32LE(16, 16); // fmt chunk size
  buf.writeUInt16LE(1, 20); // PCM
  buf.writeUInt16LE(1, 22); // mono
  buf.writeUInt32LE(sampleRate, 24);
  buf.writeUInt32LE(sampleRate, 28); // byte rate
  buf.writeUInt16LE(1, 32); // block align
  buf.writeUInt16LE(8, 34); // bits per sample
  buf.write("data", 36, "ascii");
  buf.writeUInt32LE(dataSize, 40);
  const full = resolve(path);
  mkdirSync(dirname(full), { recursive: true });
  writeFileSync(full, buf);
  return path;
}

/** Writes a labels file for `recording` with 29 word ends spaced `step` seconds apart; returns its path. */
export function labelsFile(path: string, recording: string, step = 0.5): string {
  const wordEnds = Array.from({ length: 29 }, (_, i) => Number((step * (i + 1)).toFixed(3)));
  const full = resolve(path);
  mkdirSync(dirname(full), { recursive: true });
  writeFileSync(full, JSON.stringify({ recording, wordEnds, notes: "generated by tests" }, null, 2));
  return path;
}

/** True when `npm run fetch-assets` has run (models and corpus are git-ignored). */
export function hasAssets(): boolean {
  return ["public/data/zipformer_quran.json", "public/models/zipformer_a0w_ep1_a05.int8.onnx"].every((p) =>
    existsSync(resolve(p)),
  );
}
export const NO_ASSETS = "models/corpus missing: run npm run fetch-assets";

const AUDIO = /\.(wav|mp3|m4a|aac|webm|ogg|opus|flac)$/i;

/** Absolute path of the first recording in spike/recordings that has <base>.labels.json, or null. */
export function labelledRecording(): string | null {
  const dir = resolve("recordings");
  if (!existsSync(dir)) return null;
  const files = readdirSync(dir).sort();
  const hit = files.find((f) => AUDIO.test(f) && files.includes(`${f.slice(0, f.lastIndexOf("."))}.labels.json`));
  return hit ? join(dir, hit) : null;
}

export type FakeMic = { kind: "silence" } | { kind: "deny" } | { kind: "file"; url: string };

/**
 * Init script (runs in the page, no closures): replaces getUserMedia with a stream from a fresh
 * AudioContext: zeros, a permission error, or a file fetched from `url` played once.
 * `window.fakeMic.ended` turns true when the file has finished playing.
 */
export function installFakeMic(mode: FakeMic): void {
  const state = { ended: false };
  (window as unknown as { fakeMic: typeof state }).fakeMic = state;
  navigator.mediaDevices.getUserMedia = async () => {
    if (mode.kind === "deny") throw new DOMException("denied by test", "NotAllowedError");
    const ctx = new AudioContext({ sampleRate: 16000 });
    const dest = ctx.createMediaStreamDestination();
    if (mode.kind === "silence") {
      const zero = ctx.createConstantSource();
      zero.offset.value = 0;
      zero.connect(dest);
      zero.start();
    } else {
      const bytes = await (await fetch(mode.url)).arrayBuffer();
      const player = ctx.createBufferSource();
      player.buffer = await ctx.decodeAudioData(bytes);
      player.connect(dest);
      player.onended = () => {
        state.ended = true;
      };
      player.start();
    }
    if (ctx.state === "suspended") await ctx.resume();
    return dest.stream;
  };
}

/** Refuses every non-GET /__dev/ request, so a test can never write into recordings/ or results/. */
export async function blockDevWrites(browser: Browser): Promise<void> {
  await browser.route("**/__dev/**", (route) => (route.request.method === "GET" ? route.continue() : route.abort()));
}

/**
 * Keeps the last Blob handed to URL.createObjectURL (downloadJson builds its link from it). The
 * download's own file.path is relative to the attempt's artifact directory, so tests read the JSON here.
 */
export async function captureBlobs(browser: Browser): Promise<void> {
  await browser.evaluate(() => {
    const original = URL.createObjectURL.bind(URL);
    URL.createObjectURL = (blob: Blob | MediaSource) => {
      (window as unknown as { lastBlob: Blob | MediaSource }).lastBlob = blob;
      return original(blob);
    };
    return null; // evaluate needs a JSON result
  });
}

export async function lastBlobJson<T>(browser: Browser): Promise<T> {
  const text = await browser.evaluate(() => (window as unknown as { lastBlob: Blob }).lastBlob.text());
  return JSON.parse(text) as T;
}
